server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: hmdp
  rabbitmq:
    host: 192.168.236.134
    port: 5672
    username: root
    password: root
    virtual-host: /
    listener:
      simple:
        prefetch: 1
    template:
      message-converter: org.springframework.amqp.support.converter.Jackson2JsonMessageConverter
  datasource:
    url: jdbc:mysql://192.168.236.134:3307/hmdp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.236.134
    port: 6379
    password: root
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
  configuration:
    map-underscore-to-camel-case: true # 自动驼峰映射
logging:
  level:
    com.hmdp: debug